"""empty message

Revision ID: e11a1c27aced
Revises: 
Create Date: 2021-12-05 17:44:34.435353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e11a1c27aced'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('color', sa.String(length=20), nullable=False))
    op.add_column('note', sa.Column('library_title', sa.Integer(), nullable=True))
    op.drop_constraint('note_title_fkey', 'note', type_='foreignkey')
    op.create_foreign_key(None, 'note', 'library_title', ['library_title'], ['id'])
    op.drop_column('note', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('title', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.create_foreign_key('note_title_fkey', 'note', 'title', ['title'], ['id'])
    op.drop_column('note', 'library_title')
    op.drop_column('note', 'color')
    # ### end Alembic commands ###
